Use lumen as backend api
MOPCON/MOPCON pull request #175
Opened 2019-07-06 12:50 UTC by Zames-Chang

將 lumen 當成 backend。

2019-07-07 01:03 UTC, hashman commented
先請 @xwang0929 幫忙看看，謝謝

2019-07-07 14:23 UTC, xwang0929 approved these changes
just a blank project. let's rock!

2019-07-07 14:59 UTC, hashman requested changes
Hi @Zames-Chang 雖說目前的 change 雖說是空白的 lumen 專案沒錯但是有幾個地方我希望可以讓他更貼近 initialize 的 change

1. 將沒有必要的檔案移除， Lumen initial 的時候會有很多 template 檔案，但是其實有些是我們不需要或是暫時不需要的
2. 放在 api folder 裡面但是目前的配置他是無法正常在 https://mopcon.org/api 這個 route 進行使用的，需要補上 `.htaccess` 才可以正常使用

這兩點麻煩幫忙調整，謝謝

2019-07-09 16:11 UTC, Zames-Chang commented
感謝 hash 幫忙我這個小菜雞 QQ

再麻煩 @hashman  大大過目

2019-07-10 01:23 UTC, hashman commented
Hello @Zames-Chang ,

麻煩參考這個[文件](https://www.evernote.com/l/ALaCRcY6FShNnrY5WN3Y5sYPhxqZB38unYM)將 branch 進行 rebase ，你可以看一下你現在的線圖跟我文件的線圖差異，有問題可以再提出

另外是 `api/app/Console/Commands/.gitkeep`, `api/database/migrate/.gitkeep`, `api/resources/views/.gitkeep` 這些檔案應該不需要？

過程中學習有問題就竟量提出，來參加活動或是貢獻 Open Source Project 都會希望你們有收穫與學習，花時間在有意義的事情上，也希望能夠幫助到你們

再請 Zames 幫忙一下

2019-07-10 09:42 UTC, Zames-Chang commented
我修正完畢了，再麻煩你看一下。 @hashman

2019-07-10 09:53 UTC, hashman approved these changes

2019-07-10 09:53 UTC, hashman commented
LGTM

2019-07-10 09:53 UTC, merged