Add facebook Api
MOPCON/MOPCON pull request #181
Opened 2019-07-12 13:11 UTC by Zames-Chang

釋出取得 facebook 貼文資訊的功能
再麻煩 hash 幫我測試看看可不可以用在 mopcon 上
@hashman

2019-07-13 08:41 UTC, hashman requested changes
再請 Zames 幫忙看看，謝謝

2019-07-13 08:41 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        $this->url = 'https://graph.facebook.com/mopcon/';
這個 url 可以跟上方的 protected 寫在一起就好，就不用寫在 construct 裡面了

2019-07-13 08:41 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +    public function getPosts($number)
習慣上 limit 會放在 url parameter 裡面，像是這樣 `https://mopcon.org/api/facebook/posts?limit=20` 這樣的方式

2019-07-13 08:41 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        if ($number > 100) {
這邊調整一下，預設 20 最高不要超過 100

2019-07-13 08:41 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +            return json_decode($error, true);
error response 可以參考 #183 使用 `returnError` function 進行回傳

2019-07-13 08:41 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        $token = getenv('FACEBOOK_TOKEN');
這邊可以直接用 `env` 就好了 lumen / laravel 有這個 helper function

2019-07-13 08:41 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        }
`$fields` 的 value 可以不用加上 `,` 下方直接用 `$baseUrl .= implode(',', $fields);` 就可以了

2019-07-13 08:41 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        $fields = ['full_picture,','message,','id,','created_time'];
coding style 逗號後面會加上空白 `$fields = ['full_picture,', 'message,', 'id,', 'created_time'];`

2019-07-13 08:41 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        return $dataJson['data'];
這邊可以參考 #183 使用 `returnSuccess` 來回傳，此外需要多判斷沒有 data 這個 key 的情境該怎麼處理

2019-07-13 08:41 UTC, hashman commented on api/readme.md
> +# MOPCON API
api document 開一個 folder 專門來放好了，目標可能會在 `/api/docs/facebook.md` 這邊，格式可以參考 https://gist.github.com/iros/3426278

2019-07-13 08:41 UTC, hashman commented on api/routes/web.php
> +    $router->get('posts/{number}', 'FacebookController@getPosts');
url 希望可以調整一下，用 posts 沒辦法直覺的看出來這個是 Facebook 的 API 可能可以使用

`/api/facebook/posts` 會比較直覺一點，另外是也可以參考 Controller 那邊的建議一起調整

2019-07-13 14:03 UTC, Zames-Chang commented
OK了解～

2019-07-15 13:02 UTC, hashman requested changes

2019-07-15 13:02 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        $this->url = 'https://graph.facebook.com/mopcon/';
上方還是需要 initial url 這個 parameter 唷，我的意思其實是指

```
class FacebookController extends Controller
{
    use ApiTrait;
    private $url = 'https://graph.facebook.com/mopcon/';
...
}
```

這樣 __construct 就可以拿掉了

2019-07-15 13:02 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        $limit = $request->get('limit');
second parameter 就是 default value 唷

2019-07-15 13:02 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +                $message = 'can not access over than 100 posts'
應該不需要這個 `$message`?

2019-07-15 13:02 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        if (!$dataJson['data']) {
如果沒有 data 這個 index 這邊會噴掉唷

2019-07-15 13:02 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +            $data = $dataJson['data']
這邊的 `$data` 與 `$message` parameter 是不需要的

2019-07-15 13:02 UTC, hashman commented on api/routes/web.php
> +    $router->get('posts', 'FacebookController@getPosts');
這個 url 希望可以調整成 `/api/facebook/posts` 才可以看出是 Facebook 的 api 唷

2019-07-15 14:50 UTC, Zames-Chang commented on api/app/Http/Controllers/FacebookController.php
> +                $message = 'can not access over than 100 posts'
所以如果他要求超過100篇直接給他100篇而不是給error的意思嗎？

2019-07-15 14:51 UTC, Zames-Chang commented on api/app/Http/Controllers/FacebookController.php
> +                $message = 'can not access over than 100 posts'
喔我看懂了，就是直接帶入就好了

2019-07-15 15:16 UTC, Zames-Chang commented
再麻煩 @hashman

2019-07-16 00:44 UTC, hashman requested changes
麻煩修改一下

2019-07-16 00:44 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +    private $url = 'https://graph.facebook.com/602218626874063/';
url 錯了

2019-07-16 05:31 UTC, Zames-Chang commented on api/app/Http/Controllers/FacebookController.php
> +    private $url = 'https://graph.facebook.com/602218626874063/';
OK 修改了～

2019-07-17 00:13 UTC, hashman approved these changes

2019-07-17 00:14 UTC, hashman commented
LGTM

2019-07-17 00:14 UTC, merged