增加贊助商 api doc + 修正 facebook api doc
MOPCON/MOPCON pull request #195
Opened 2019-07-29 10:44 UTC by Zames-Chang

@hashman 麻煩你了

2019-07-29 14:57 UTC, hashman requested changes

2019-07-29 14:57 UTC, hashman commented on api/docs/sponser.md
> +        'sponsers' : [
試想一下你是前端 / client 或是你是拿這個 API 來串接的人，如果你要用 Sponsor Type 來顯示每個 sponsor type 的 sponsors 你拿到的 API 是什麼樣子才會好用呢？

2019-07-29 14:57 UTC, hashman commented on api/docs/sponser.md
> +            'type' : 'Bruce Wayne'
https://d.pr/i/ZaQ5m2

這邊還有缺少一些資訊
1. 贊助商的公司名稱除了中文之外還會有英文顯示名稱
2. 頁面上會有贊助商公司的簡介文字，簡介文字也會分中英文
3. 瞭解更多按扭會連結到贊助商提供的 url 上面
4. 除了官網之外，有些贊助商還會提供他們的 Facebook 讓我們呈現

另外這張圖好像沒有提供給你，就是 web 版的介面 https://d.pr/i/XcH5pD

web 版的介面除了可以顯示公司資訊外，也會有該公司相關獎者資訊與議程資訊，但這塊可能要跟講者 API 搭配處理才可以互動

先參考一下，謝謝

2019-07-29 14:58 UTC, hashman commented
下次記得要補上 issue id link 一下，謝謝

2019-07-30 09:05 UTC, Zames-Chang commented on api/docs/sponser.md
> +        'sponsers' : [
```
data : 
  'Bruce Wayne' : [
    {
      'logo_path' : 'https://path/to/kkbox/logo', 
      'sponser' : 'kkbox'
    } 
  ],
 ...
```

2019-07-30 09:05 UTC, Zames-Chang commented on api/docs/sponser.md
> +        'sponsers' : [
這樣如何？

2019-07-30 09:06 UTC, Zames-Chang commented on api/docs/sponser.md
> +            'type' : 'Bruce Wayne'
ＯＫ 之前沒收到那張圖，我再根據上面需要的資訊做設計

2019-07-30 10:44 UTC, hashman commented on api/docs/sponser.md
> +        'sponsers' : [
可以但是 index key 通常不會有空白

2019-07-30 10:45 UTC, hashman commented on api/docs/sponser.md
> +            'type' : 'Bruce Wayne'
謝謝

2019-07-31 16:21 UTC, Zames-Chang commented
我根據需要的資料做了新增，但是有 url parameter 應該要與沒有 url parameter 的時候結構一致，但目前我覺得沒有一致前端那邊感覺會比較好做。

2019-07-31 23:22 UTC, hashman requested changes
很清楚了，一些小細節再調整就好了，謝謝

2019-07-31 23:22 UTC, hashman commented on api/docs/sponser.md
> +                'speaker_time' : '15:00'
這邊幫忙先補上 session_room 好了，知道時間但是不知道是那個 room 還是需要反查議程表，這樣就不直覺了，但是設計圖上面沒有，我再跟設計師溝通一下

2019-07-31 23:22 UTC, hashman commented on api/docs/sponser.md
> +        'special_thank' : [
應該是 thanks? xD

2019-07-31 23:22 UTC, hashman commented on api/docs/sponser.md
> +    `/api/sponsor?company=kkbox,google`
這邊的 company 看起來是對應到 sponsor_en 這個欄位，但是 sponsor_en 通常會是大寫或是會有很多的字母組成，或許可以再欄位中多增加一個 id / nick 之類的欄位來做 mapping 如何？

2019-07-31 23:22 UTC, hashman commented on api/docs/sponser.md
> +Returns json data about a sponsor information.
about a sponsor? 應該不是單一 sponsor 的資訊？

2019-07-31 23:22 UTC, hashman commented on api/docs/sponser.md
> +  company = {company_name_en}
區分一下 require 跟 options 這邊應該是 options 才對

2019-08-03 08:31 UTC, Zames-Chang commented
OK 根據已據需求修正

2019-08-03 12:29 UTC, hashman approved these changes

2019-08-03 12:30 UTC, hashman commented
ok 我覺得沒問題了，可以先產 mock api 給 client 接了，謝謝

2019-08-03 12:30 UTC, merged