add: 主辦社群與參與社群 doc
MOPCON/MOPCON pull request #204
Opened 2019-08-01 15:43 UTC by FWcloud916

#170 @hashman @hsimao 再麻煩幫我看一下

2019-08-02 01:55 UTC, hashman requested changes

2019-08-02 01:55 UTC, hashman commented on api/docs/community.md
> +        "1": {
要不要將 id 改為自定義的 nickname 呢？如 gdg-cloud-kh, kh-py 等等等，這樣在找單一資料的時候可能會比較直覺一點

2019-08-02 01:55 UTC, hashman commented on api/docs/community.md
> +    GDG Kaohsiung
introduction 的部分要注意一下，因為是 api 所以統一都是要出 `\n` 換行的文字，不可以是 html ，這樣才可以讓不同的 client platform 自行進行處理

2019-08-02 01:55 UTC, hashman commented on api/docs/community.md
> +  ```
少定義錯誤的情況，舉例如果取不到檔案，或是檔案的格式不如預期等

2019-08-02 03:11 UTC, FWcloud916 commented on api/docs/community.md
> +        "1": {
可以看看對前端來說，那一種比較方便操作

2019-08-02 14:43 UTC, FWcloud916 commented
@hashman 有調整了 在麻煩看一下 謝謝

2019-08-02 15:03 UTC, hashman commented on api/docs/community.md
> +        "1": {
@Tzuhui 覺得呢？

2019-08-03 12:32 UTC, hashman commented on api/docs/community.md
> +        "1": {
用 id 沒關係，但 key 應該就不需要了， object 裡面有 id 欄位就可以哩

2019-08-03 14:05 UTC, Tzuhui commented on api/docs/community.md
> +        "1": {
這邊我覺得這樣就可以～

2019-08-03 15:26 UTC, FWcloud916 commented
@hashman 調整了，麻煩看一下，謝謝

2019-08-04 07:10 UTC, hashman commented on api/docs/community.md
> +        "1": {
這個 json 格式是錯誤的唷， organizer 應該要是 array? 社群的話感覺上用 community 會比較好一點

2019-08-05 03:36 UTC, FWcloud916 commented on api/docs/community.md
> +        "1": {
@hashman  調整了，是因為結尾多了一些逗號，我有改成用 array。
看設計稿的圖片好像沒有特別區分主辦跟參與，請問是不需要區分還是漏掉了?

2019-08-05 06:03 UTC, hashman commented on api/docs/community.md
> +        "1": {
先這樣保留沒關係，之後可以再調整

2019-08-05 06:03 UTC, hashman approved these changes

2019-08-05 06:03 UTC, hashman commented
ok 先這樣，也麻煩 @FWcloud916 可以先進入 API 開發的階段了，謝謝

2019-08-05 06:04 UTC, merged