Feature/sponser api
MOPCON/MOPCON pull request #206
Opened 2019-08-06 15:34 UTC by Zames-Chang

#171 
先用mock的假資料做一個api讓前端可以先串接
@hashman

2019-08-07 00:54 UTC, hashman requested changes

2019-08-07 00:54 UTC, hashman commented on api/app/Http/Controllers/SponserController.php
> +class SponserController extends Controller
沒有發現一直以來你都拼錯 xDD 是 `sponsor` 不是 `sponser`

2019-08-07 00:54 UTC, hashman commented on api/app/Json/mockSponser.json
> +    "sponsers_map":{
這個 map 應該不太需要，至於為什麼你可以用 client 的思路去思考為什麼不需要

2019-08-07 00:54 UTC, hashman commented on api/app/Json/mockSponser.json
> +            "logo_path" : "https://www.logaster.com/blog/wp-content/uploads/2018/05/LogoMakr.png",
coding style 冒號前面不會有空白

2019-08-07 00:54 UTC, hashman commented on api/app/Json/mockSponser.json
> +            [
json style guideline 可以看一下

https://google.github.io/styleguide/jsoncstyleguide.xml

2019-08-07 00:54 UTC, hashman commented on api/app/Json/mockSponser.json
> +    "sponsers": {
這個已經是 sponsor 的 json data 了，應該不需要再寫 sponsor? 另外是應該要是 array 包住所有的 sponsor 資料

2019-08-07 00:54 UTC, hashman commented on api/app/Http/Controllers/SponserController.php
> +        $sponsers = file_get_contents(dirname(__FILE__).'/../../Json/mockSponser.json');
以 laravel 為例，他的 asset 會放在 `resource/assets` 中，或許把 json 放在那邊會比較適合，舉例 `resource/assets/json/` 這個位置

此外可以將 `dirname(__FIR__)` 取代為 `__DIR__` 就可以了

coding style `.` 的左右會留空白

2019-08-07 00:54 UTC, hashman commented on api/app/Json/mockSponser.json
> +            "sponser_en" : "google",
如果搜尋要用 sponsor_id 的話，我個人 prefer 用目前你定義的 `sponsor_en` 來輸入，看起來更為直覺

2019-08-07 00:54 UTC, hashman commented on api/app/Http/Controllers/SponserController.php
> +     * @return json
雖說 json 很直覺沒錯，但其實 PHP 並沒有定義這種 type ，以這邊為例應該是 `\Illuminate\Http\JsonResponse` 會比較適合

https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

2019-08-07 00:54 UTC, hashman commented on api/app/Http/Controllers/SponserController.php
> +    public function getAllSponsers(Request $request)
雖說 Lumen 已經沒有像 Laravel 一樣有實做 resource Controller 這個東西，需要自行定義所有的 routing 但是還是希望可以 follow Laravel 已經定義好的 Restful 架構實做，詳細可以參考[這邊](https://laravel.com/docs/5.8/controllers#resource-controllers)

以這個 function 為例，應該要定義為 index

2019-08-07 00:54 UTC, hashman commented on api/app/Http/Controllers/SponserController.php
> +        return $this->returnSuccess('Success', $sponsersData);
其實可以將這邊的 return 搬到 28 行，就不需要下面的 else 了

2019-08-07 00:54 UTC, hashman commented on api/app/Http/Controllers/SponserController.php
> +        $sponsersId = $request->get('sponser_id', '');
這邊定義的跟你 api document 的不一樣唷，另外是 sponsor_ids 會比較吻合情況

2019-08-07 00:54 UTC, hashman commented on api/routes/web.php
> +        $router->get('map', 'SponserController@getSponsersMap');
map 這個 API 我覺得應該不太需要

2019-08-09 08:57 UTC, Zames-Chang commented
@hashman  我幾乎重寫了ORZ～ 可能要麻煩你重新看一遍了ＸＤ

2019-08-10 23:42 UTC, hashman commented on api/app/Http/Controllers/SponserController.php
> +class SponserController extends Controller
```
╭─hashman@hash-personal-ubuntu ~/repo/MOPCON/api ‹ruby-2.6.3› ‹feature/sponserApi›
╰─➤  ag sponser
app/Http/Controllers/SponsorController.php
12:     * Get all or specific Sponsers information.
21:        return count($sponsorIdArr) ? $this->getSpecificSponsers($sponsorJson, $sponsorIdArr) : $this->getAllSponsers($sponsorJson);
23:    private function getAllSponsers($sponsorJson)
40:    private function getSpecificSponsers($sponsorJson, $sponsorIdArr)
```

2019-08-10 23:54 UTC, hashman requested changes
再請 @Zames-Chang 看看，謝謝

2019-08-10 23:54 UTC, hashman commented on api/docs/sponsor.md
> +    `/api/sponsor`
幫忙多補充 `/api/sponsor?sponsor_id=g01` 的用法與 Response

2019-08-10 23:54 UTC, hashman commented on api/tests/Feature/Controller/SponsorControllerTest.php
> +        $id = ['g1','a1','a2'];
coding style 逗號後面留上空白，謝謝

2019-08-11 14:07 UTC, Zames-Chang commented
ＯＫ

2019-08-12 01:54 UTC, hashman commented on api/app/Http/Controllers/SponserController.php
> +class SponserController extends Controller
LGTM

```
╭─hashman@hash-personal-ubuntu ~/repo/MOPCON/api ‹ruby-2.6.3› ‹feature/sponserApi›
╰─➤  ag sponser
```

2019-08-12 01:57 UTC, hashman commented on api/tests/Feature/Controller/SponsorControllerTest.php
> +        $id = ['g1','a1','a2'];
沒有注意到一個東西，幫忙調整路徑與 namespace 一致， namespace 是 `app\Http\Controller`

2019-08-12 02:22 UTC, hashman requested changes
此外有些東西我有寫在 slack 中再請 @Zames-Chang 看看

2019-08-12 02:22 UTC, hashman commented on api/app/Http/Controllers/SponsorController.php
> +            'sponsor_types' => $this->sponsorTypes
確認一下這個是必要的嗎？看起來 API Document 沒有這個欄位

2019-08-12 02:22 UTC, hashman commented on api/tests/Feature/Controller/SponsorControllerTest.php
> +        $id = ['aaa','bbb'];
coding style

2019-08-12 13:56 UTC, Zames-Chang commented on api/tests/Feature/Controller/SponsorControllerTest.php
> +        $id = ['aaa','bbb'];
這個實在錯太多次了，我直接在phpcsfixer上面設定強制幫我做這件事了

2019-08-12 14:00 UTC, Zames-Chang commented on api/app/Http/Controllers/SponsorController.php
> +            'sponsor_types' => $this->sponsorTypes
api doc上有，但的確好像沒有很必要我會把它拿掉

2019-08-12 14:39 UTC, Zames-Chang commented
ok

2019-08-12 14:46 UTC, hashman requested changes

2019-08-12 14:46 UTC, hashman commented on api/tests/app/Http/Controllers/SponsorControllerTest.php
> +        $sponsorfilePath = __DIR__ . '/../../../../resource/assets/json/' . (env('APP_ENV') == 'production' ? 'sponsor.json' : 'sponsor-dev.json') ;
預設的 APP_ENV 是 production 所以如果沒有給 APP_ENV 應該要給 production 的 path

2019-08-13 14:58 UTC, Zames-Chang commented
rebased it

2019-08-14 14:52 UTC, Zames-Chang commented
再次的merge了 @hashman

2019-08-14 15:27 UTC, hashman approved these changes

2019-08-14 15:27 UTC, merged