主辦社群與參與社群 API
MOPCON/MOPCON pull request #208
Opened 2019-08-09 05:27 UTC by FWcloud916

#170 @hashman 好了，麻煩幫我檢查。
另外，我有稍微修改 doc 增加錯誤的 response 跟修改回傳的 data 格式，
也麻煩幫我看一下有沒有問題，謝謝!

2019-08-10 06:57 UTC, FWcloud916 commented
@hashman 拆開了，再麻煩幫我看一下，謝謝

2019-08-11 02:41 UTC, hashman requested changes
麻煩 @FWcloud916 再看看，謝謝

2019-08-11 02:41 UTC, hashman commented on api/docs/community.md
> +    "data": [
這邊改城陣列的原因是？看實際結構應該不是

2019-08-11 02:41 UTC, hashman commented on api/docs/community.md
> +    "data": [
這邊改成陣列的原因是？看程式碼好像只會允許一次搜尋一個

2019-08-11 02:41 UTC, hashman commented on api/resource/assets/json/volunteers.json
> +    "volunteer": [
這個 json 已經是給 volunteer 的，應該就不用再分類了

2019-08-11 02:41 UTC, hashman commented on api/resource/assets/json/communties.json
> +    "community": [
這個 json 已經是給 communities 的了，應該就不用再分類了

2019-08-11 04:42 UTC, FWcloud916 commented on api/docs/community.md
> +    "data": [
```javascript
public function returnSuccess($message = '', $data = [], $field = [])
    {
        $field['data'] = $data;
        return response()->json(array_merge([
            'success' => true,
            'message' => $message,
        ], $field), 200);
    }
```
我用這個回傳，好像會被包進 array ，所以才修改這邊

2019-08-11 06:06 UTC, FWcloud916 commented on api/docs/community.md
> +    "data": [
@hashman 跟上面一樣

2019-08-11 06:07 UTC, FWcloud916 commented on api/resource/assets/json/communties.json
> +    "community": [
@hashman 所以參與社群跟主辦社群不用特別區分開來嗎？

2019-08-11 06:08 UTC, FWcloud916 commented on api/resource/assets/json/volunteers.json
> +    "volunteer": [
ok

2019-08-11 15:14 UTC, hashman commented on api/docs/community.md
> +    "data": [
這邊的話 `$data` 被 merge 進去只是多了一個 data 的 key 在陣列中，對於 data 來說他是 json object 的結構，那 data 本身是 json object 還是 json array 就要看送入 $data 的東西

2019-08-11 17:41 UTC, FWcloud916 commented
@hashman 調整好了，再麻煩幫我看一下。

> @hashman 所以參與社群跟主辦社群不用特別區分開來嗎？

如果不用區分主辦社群跟參與社群，我想直接合在一起，再麻煩幫我回答一下。謝謝~

2019-08-11 23:35 UTC, hashman commented on api/resource/assets/json/communties.json
> +    "community": [
Hi @FWcloud916 我想要表達的事情是目前已經有區分 communities.json 與 volunteers.json 兩個 json file 了，所以在 communities.json 裡面應該就不需要 community 這個 key 了，在 volunteers.json 中也不需要 volunteer 這個 key

2019-08-11 23:38 UTC, hashman commented on api/resource/assets/json/communties.json
> +    "community": [
Sorry 我誤會了，我沒有看到 participant 這個東西，需求上是需要區分這兩個東西的，目前這樣的結構我覺得可以沒問題

2019-08-11 23:39 UTC, hashman commented on api/resource/assets/json/volunteers.json
> +    "volunteer": [
這個好像還沒調整到

2019-08-11 23:40 UTC, FWcloud916 commented on api/resource/assets/json/communties.json
> +    "community": [
Ok，謝謝～

2019-08-13 00:51 UTC, hashman approved these changes
LGTM

2019-08-13 00:51 UTC, merged