Feature/unconf api
MOPCON/MOPCON pull request #221
Opened 2019-08-16 15:10 UTC by Zames-Chang

@hashman  

2019-08-17 12:27 UTC, hashman requested changes
`unconf.json` 可以用個 empty array 來存放
其他的麻煩 @Zames-Chang 再看看，另外是再幫忙 rebase 一下，謝謝

2019-08-17 12:27 UTC, hashman commented on api/app/Http/Controllers/UnconfController.php
> +    public function index(Request $request)
`$request` 沒有使用到

2019-08-17 12:27 UTC, hashman commented on api/app/Http/Controllers/UnconfController.php
> +            '10/9' => []
MOCON 今年的時間是 10/19 - 20 唷，另外是我在想，如果 json 裡面已經有日期了，這邊應該就不用 hard code 一個日期的 array key 了？依照 json 的內容來產生就好

2019-08-17 12:27 UTC, hashman commented on api/docs/facebook.md
>        'success' : true,
看到順便說一下， json 使用的 string 是用雙引號

2019-08-20 17:40 UTC, Zames-Chang commented
OK

2019-08-21 01:07 UTC, hashman approved these changes
LGTM

2019-08-21 01:07 UTC, merged