主要議程 api spec
MOPCON/MOPCON pull request #229
Opened 2019-08-18 12:12 UTC by FWcloud916

#197 
@hashman 麻煩幫我看一下。謝謝

2019-08-18 12:20 UTC, hashman requested changes

2019-08-18 12:20 UTC, hashman commented on api/docs/conf.md
> +    /api/2019/conf
用 session 可能會比較好

2019-08-18 12:20 UTC, hashman commented on api/docs/conf.md
> +  ```JSON
小寫 json

2019-08-18 12:20 UTC, hashman commented on api/docs/conf.md
> +                  "keynote"
我在想 keynote 的部分使用另外一個 key 會不會比較好判斷呢？

2019-08-18 12:20 UTC, hashman commented on api/docs/conf.md
> +                  "禁止攝影"
tag 的部分看起來有四個項目

1. 是不是 keynote
2. 是不是 sponsor session
3. 可不可以攝影
4. 難易度

每個 tag 都有些客制化的設定，要不要直接用成參數給 client 去自由實做就好了呢？

2019-08-18 12:51 UTC, FWcloud916 commented on api/docs/conf.md
> +                  "keynote"
keynote 在 UI 上被歸類 topic tags 中的其他，我覺得還是維持在這邊比較好

2019-08-18 12:51 UTC, FWcloud916 commented on api/docs/conf.md
> +                  "禁止攝影"
1. 這邊的 keynote 應該是我誤植XD
2~4 屬於 session tags 改成參數

2019-08-18 12:51 UTC, FWcloud916 commented on api/docs/conf.md
> +    /api/2019/conf
OK

2019-08-18 12:51 UTC, FWcloud916 commented on api/docs/conf.md
> +  ```JSON
OK

2019-08-18 12:52 UTC, FWcloud916 commented
@hashman 好了喔，在麻煩看一下

2019-08-18 12:53 UTC, FWcloud916 commented on api/docs/conf.md
> +                "difficulty": "Basic"
session tags 改成參數

2019-08-18 13:29 UTC, hashman commented on api/docs/conf.md
> +  ```JSON
小寫 json

2019-08-18 13:29 UTC, hashman commented on api/docs/conf.md
> +  ```JSON
小寫 json

2019-08-18 13:29 UTC, hashman commented on api/docs/conf.md
> +                "difficulty": "Basic"
level 可能會比較好

2019-08-18 13:29 UTC, hashman commented on api/docs/conf.md
> +                  "禁止攝影"
keynote 不獨立出來嗎？或是 tag_other 被你定義為放置什麼東西使用的呢？

2019-08-19 17:31 UTC, FWcloud916 commented
@hashman 在麻煩看一下

2019-08-19 21:58 UTC, hashman approved these changes

2019-08-19 21:59 UTC, hashman commented
LGTM

2019-08-19 21:59 UTC, merged