Fix Bug in doc and Json
MOPCON/MOPCON pull request #231
Opened 2019-08-21 14:45 UTC by Zames-Chang

1. 修正 facebook.md 中的 json 格式錯誤
2. 修正 sponsor-dev.json 中的資料，同時修正 sponsor.md 輸出的結果

@hashman

2019-08-21 23:54 UTC, hashman requested changes

2019-08-21 23:54 UTC, hashman commented on api/docs/facebook.md
>                ...
要吻合 json 格式這邊也是錯誤的唷，是不可以用 ... 來描述

2019-08-21 23:54 UTC, hashman commented on api/docs/facebook.md
> +              "shares": {int}, // 多少人分享
json 裡面是不允許註解的，改為在文件上面描述清楚就好，或是其實可以不用描述也沒關係

2019-08-22 15:07 UTC, Zames-Chang commented
OK

2019-08-22 15:12 UTC, hashman requested changes
其實 api document 意思與結構有傳達到就好，不一定真的要貼這麼多 row 出來

2019-08-22 15:12 UTC, hashman commented on api/docs/facebook.md
> +        "message": "can not access over than 100 posts"
少了 `,`

2019-08-22 15:12 UTC, hashman commented on api/docs/facebook.md
> +        "message": "Token invalid"
少了 `,`

2019-08-22 15:28 UTC, Zames-Chang commented
OK

2019-08-22 15:51 UTC, hashman approved these changes

2019-08-22 15:51 UTC, merged