主要議程 api 實作
MOPCON/MOPCON pull request #232
Opened 2019-08-21 18:36 UTC by FWcloud916

#197 
1. 增加議程難易資訊(原本是要加 CC 但是我看錯了其實是難易資訊 XD)
2. 調整議程 doc 修改回傳內容及增加一個 api 來取得議程清單(非時間表)
3. 議程 api 實作

@hashman 麻煩幫我檢查，感謝!

2019-08-21 23:51 UTC, hashman requested changes
session.json 還是要先補上去，用 empty array 來處理即可

2019-08-21 23:51 UTC, hashman commented on api/app/Http/Controllers/SessionController.php
> +        }
有使用 Controller 所提供的 helper function 了，這邊應該就不需要額外在去抓 json 了？

2019-08-21 23:51 UTC, hashman commented on api/app/Http/Controllers/SessionController.php
> +            $this->session[$speaker['speaker_id']] = $this->transSpeakerToSession($speaker);
session 的 index key 可能不可以用 speaker_id 來用，因為可能會有一個 speaker 講兩場的情況，雖說蠻少見的，但可能還是用 session_id 會比較適合一點

2019-08-22 15:38 UTC, hashman commented on api/app/Http/Controllers/SessionController.php
> +        }
Sorry 我看錯了... 這邊這樣沒關係

2019-08-22 18:31 UTC, FWcloud916 commented
@hashman 調整了，再麻煩看一下

2019-08-23 01:01 UTC, hashman requested changes
這個請 @FWcloud916 再幫忙一下，謝謝

2019-08-23 01:01 UTC, hashman commented on api/app/Http/Controllers/SessionController.php
> +            $speakers = json_decode(file_get_contents(__DIR__ . '/../../../resource/assets/json/speaker.json'), true);
這邊調整一下好了，幫我將 `app/Http/Controllers/Controller.php` 的 `$path` 改為 protected ，這邊就可以改成

```
$speakers = json_decode(file_get_contents($this->path . 'speaker.json'));
```

這樣看起來會更為簡短

2019-08-23 15:34 UTC, FWcloud916 commented
@hashman 好了喔，麻煩看一下

2019-08-23 15:34 UTC, FWcloud916 commented on api/app/Http/Controllers/SessionController.php
> +            $speakers = json_decode(file_get_contents(__DIR__ . '/../../../resource/assets/json/speaker.json'), true);
OK

2019-08-23 15:37 UTC, FWcloud916 commented
rebase

2019-08-23 22:43 UTC, hashman approved these changes
LGTM

2019-08-23 22:44 UTC, merged