add: session api 增加 tag 篩選於主要議程清單
MOPCON/MOPCON pull request #239
Opened 2019-08-25 15:49 UTC by FWcloud916

#170 
增加 tag 篩選於主要議程清單 api
`/api/2019/session/list`
`/api/2019/session/list?tags=:tags`

@hashman 好了，麻煩幫我檢查

2019-08-26 01:10 UTC, hashman requested changes
麻煩 Eric 看看，謝謝

2019-08-26 01:10 UTC, hashman commented on api/docs/session.md
> +    /api/2019/session/list?tags=:tags
文件幫忙補充一下這個是用於什麼畫面使用的，謝謝

2019-08-26 01:10 UTC, hashman commented on api/app/Http/Controllers/SessionController.php
> +        if ($tags !== '') {
我的話可能會用反向的寫法你參考一下

```
if ($tag === '') {
   return $this->returnSuccess('success', array_values($this->sessions));
}
```

下面維持，這樣可以更短唷

2019-08-26 01:10 UTC, hashman commented on api/app/Http/Controllers/SessionController.php
> +                return false;
上面 if 可以改為下面這樣就可以了

```
return $tags === $intersect;
```

2019-08-26 16:05 UTC, FWcloud916 commented
@hashman 好了喔

2019-08-27 01:21 UTC, hashman requested changes
我確認一下，針對昨天會議提出的內容會在這個 PR 一起完成還是會另外開一個 PR 處理？

2019-08-27 01:21 UTC, hashman commented on api/docs/session.md
> +提供議程清單，主要搭配使用於需實作篩選的頁面
markdown coding style 上下留空白行，另外是我在想說如果這樣寫會不會比較清楚？「提供過濾議程標籤後的議程清單」這樣會不會比較簡單又直覺？

2019-08-27 02:23 UTC, FWcloud916 commented
> 我確認一下，針對昨天會議提出的內容會在這個 PR 一起完成還是會另外開一個 PR 處理？

我會想另外開一個來處理

2019-08-27 02:24 UTC, hashman commented
> > 我確認一下，針對昨天會議提出的內容會在這個 PR 一起完成還是會另外開一個 PR 處理？
> 
> 我會想另外開一個來處理

收到，那就這個 request 改好就好

2019-08-27 13:41 UTC, FWcloud916 commented
@hashman 好了，有先把 summary 補上去

2019-08-27 15:02 UTC, hashman approved these changes
LGTM

2019-08-27 15:02 UTC, merged