Update Docs
MOPCON/MOPCON pull request #244
Opened 2019-08-29 07:04 UTC by Zames-Chang

update
1. facebook.md
2. unconf.md
3. news.md

2019-08-29 07:40 UTC, hashman requested changes
UnConference 的格式需要對齊 session 的格式

2019-08-29 07:40 UTC, hashman commented on api/docs/news.md
> +1. 最近更新的消息會在 array 的前端，較舊的則會在 array 的尾端，直接跑回圈依序呈現 api 所提供的資訊即可， API 已經有排序過了
其實可以直接寫「排序為由新消息到舊消息」這樣就可以了

2019-08-29 07:40 UTC, hashman commented on api/docs/news.md
> +- link: 對應到該消息的 facebook 文章
facebook 文章？

2019-08-29 07:40 UTC, hashman commented on api/docs/news.md
> +- id(string): 對應該消息的 id
id 是 string?

2019-08-29 07:40 UTC, hashman commented on api/docs/news.md
> +- link: 對應到該消息的 facebook 文章
上面三個欄位沒有給予型態

2019-08-29 07:40 UTC, hashman commented on api/docs/news.md
> +                "id": "6",
int

2019-08-29 07:40 UTC, hashman commented on api/docs/unconf.md
> +1. 時間有呈現順序，直接跑回圈依序呈現 api 所提供的資訊即可， API 已經有排序過了
`回圈` typo

其實排序這個可以不用說

2019-08-29 12:12 UTC, Zames-Chang commented on api/docs/news.md
> +- id(string): 對應該消息的 id
這個因為 facebook api id規則是 id(String): {mopcon_id}_{posts_id} 
e.x. id: "1234_5678"

2019-08-29 12:13 UTC, Zames-Chang commented on api/docs/news.md
> +- id(string): 對應該消息的 id
還是先給int 到時候我們後端自己在 map

2019-08-29 12:55 UTC, Zames-Chang commented on api/docs/news.md
> +- link: 對應到該消息的 facebook 文章
由於 #199 說格式同去年，因此我從去年的 news.json 拿的假資料，其中
"link": "https://www.facebook.com/mopcon/posts/1786796171446091" 的確是對應到 facebook 文章

2019-08-29 12:56 UTC, Zames-Chang commented on api/docs/news.md
> +- link: 對應到該消息的 facebook 文章
還是應該修改為`對應到該消息的連結會比較好`

2019-08-29 13:01 UTC, Zames-Chang commented on api/docs/unconf.md
> +1. 時間有呈現順序，直接跑回圈依序呈現 api 所提供的資訊即可， API 已經有排序過了
那 sponsor.md 的回圈也打錯了，我順便修正掉喔

2019-08-29 15:06 UTC, hashman commented on api/docs/news.md
> +- link: 對應到該消息的 facebook 文章
yes

2019-08-29 15:08 UTC, hashman commented on api/docs/news.md
> +- link: 對應到該消息的 facebook 文章
這個好像沒有調整到

2019-08-29 15:10 UTC, Zames-Chang commented on api/docs/news.md
> +- link: 對應到該消息的 facebook 文章
摁摁刻意的，因為要先跟你確定一下再改

2019-08-29 15:16 UTC, hashman requested changes

2019-08-29 15:16 UTC, hashman commented on api/docs/facebook.md
> +- id(string): 對應該貼文的 id
string?

2019-08-29 15:16 UTC, hashman commented on api/docs/news.md
> +- link(string): 對應到該消息的 facebook 文章
應該是消息 Url 比較適合

2019-08-29 15:16 UTC, hashman commented on api/docs/news.md
> +- id(string): 對應該消息的 id
string?

2019-08-29 15:16 UTC, hashman commented on api/docs/news.md
> +- link(string): 對應到該消息的 facebook 文章
同上，消息 url  比較適合

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +- date(int): 當天 0 點 0 分 0 秒的 timestamp
應該是 timestamp

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +    - is_keynote(bool): 是否為 keynote 議程
這邊註記一下，恆為 false

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +      - mobile(string): 手機版使用
UnConf 應該是不會提供講者圖片的，所以這邊要注意會是 empty string

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +    - session_id(int): 議程編號，會與 speaker_id 一樣
根據 slack 的討論 session_id 不等於 speaker_id 麻煩幫忙調整一下，謝謝

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +            "isBroadCast": true,
UnConf 的 `isBroadCast` 應該是 false

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +                "is_keynote": true,
UnConf 沒有 keynote 所以應該恆為 false

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +                "room": "R2",
統一叫做 UnConf 好了

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +                "floor": "4F",
3F

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +                  "mobile": "https://picsum.photos/200"
不會給圖片，都給 empty string

2019-08-29 15:16 UTC, hashman commented on api/docs/unconf.md
> +              {
UnConf 同時段只有一個議程而已，所以不會有同時很多議程的狀況出現

2019-08-29 15:16 UTC, hashman commented on api/docs/news.md
> +- link: 對應到該消息的 facebook 文章
ok

2019-08-29 15:20 UTC, Zames-Chang commented on api/docs/facebook.md
> +- id(string): 對應該貼文的 id
這要跟你討論一下，因為 facebook api 給的 id 是 string
且 格式是 id: "{int}_{int}"

2019-08-29 15:21 UTC, hashman commented on api/docs/facebook.md
> +- id(string): 對應該貼文的 id
ok 那就是 string

2019-08-29 15:26 UTC, Zames-Chang commented on api/docs/unconf.md
> +                "floor": "4F",
樓層的邏輯是啥?是不可能有 4f 嗎?

2019-08-29 15:27 UTC, hashman commented on api/docs/unconf.md
> +                "floor": "4F",
UnConf 一定在 3F ，場地配置的關係

2019-08-29 23:27 UTC, hashman commented on api/docs/unconf.md
> +- date(int): 當天 0 點 0 分 0 秒的 timestamp
我不是這個意思耶，我的意思是說，欄位的型態應該要是 timestamp?

2019-08-29 23:40 UTC, hashman requested changes
再麻煩調整一下，其他的我沒問題了

2019-08-29 23:40 UTC, hashman commented on api/docs/news.md
> +- timestamp(timestamp): 消息產生的時間點，單位為秒
這個也是，其實我是指 timestamp 這個資料格式，如果是欄位的話要叫做 date 或是 datetime 或是 time 都可以，統一就好

2019-08-29 23:40 UTC, hashman commented on api/docs/news.md
> +- timestamp(timestamp): 消息產生的時間點，單位為秒
同上

2019-08-29 23:40 UTC, hashman commented on api/docs/unconf.md
> +- timestamp(int): 當天 0 點 0 分 0 秒的 timestamp
這個的欄位格式需要對齊 session api 欄位的名稱也是要一致的

2019-08-30 12:56 UTC, hashman approved these changes
LGTM

2019-08-30 12:56 UTC, merged