規劃 App 首頁 api doc
MOPCON/MOPCON pull request #246
Opened 2019-08-29 09:33 UTC by FWcloud916

#192 
@hashman 好了，這個也麻煩看一下喔，謝謝

2019-08-29 15:26 UTC, hashman requested changes
這個 API 有點尷尬，他會需要跟個人資訊綁定，所以看起來... 可能他的 API 要放在大地遊戲 APP 上面，這個要想想...

2019-08-29 15:26 UTC, hashman commented on api/docs/home.md
> +- session(string): 代表為喜愛議程清單
應該是 array 而且需要標明可能會是 empty array

2019-08-29 15:26 UTC, hashman commented on api/docs/home.md
> +- news(string): 代表為最新消息清單
最上方好像還有輪播的圖片，這個需求跟 PM 確認一下，除了圖片之外或許他是可以點擊的

2019-08-29 15:30 UTC, FWcloud916 commented on api/docs/home.md
> +- news(string): 代表為最新消息清單
我以為那是廣告XD

2019-08-29 15:34 UTC, FWcloud916 commented
@hashman 調整囉，我會在跟 PM 確認一下上方的圖片用意

2019-08-29 23:23 UTC, hashman commented on api/docs/home.md
> +- session(string): 代表為喜愛議程清單
session 的結構應該要是 array 才對！？

2019-08-29 23:24 UTC, hashman commented on api/docs/home.md
> +- news(string): 代表為最新消息清單
news 應該也是 array 的格式

2019-08-29 23:50 UTC, FWcloud916 commented
@hashman 加上 banner 的調整

2019-08-31 01:50 UTC, hashman requested changes

2019-08-31 01:50 UTC, hashman commented on api/docs/home.md
> +- session(array): 代表為喜愛議程清單，沒有則為 empty array
根據昨天的討論 session 區塊就不用提供了

2019-09-04 15:49 UTC, FWcloud916 commented
@hashman 調整了

2019-09-05 01:27 UTC, hashman requested changes
再麻煩幫忙，謝謝

2019-09-05 01:27 UTC, hashman commented on api/docs/home.md
> +  - id(int): 最新消息 ID
Hi @FWcloud916 我想了一下我們 news 的結構應該要跟 news api 的結構是一致的，這樣才會有彈性給 APP 進行使用，舉例來說可能要點擊彈跳出詳細的資訊等等

https://github.com/MOPCON/MOPCON/blob/develop/api/docs/news.md

2019-09-05 07:58 UTC, FWcloud916 commented
@hashman 調整了，順便問一下，需要規定只提供最新 N 則消息嗎?

2019-09-05 15:44 UTC, hashman commented
> @hashman 調整了，順便問一下，需要規定只提供最新 N 則消息嗎?

先不要限制好了

2019-09-05 15:45 UTC, hashman approved these changes
LGTM

2019-09-05 15:45 UTC, merged