新增講者頁面
MOPCON/MOPCON pull request #247
Opened 2019-08-30 15:40 UTC by Tzuhui

#220 新增講者頁面，再請 @hashman 幫忙 review，感謝 :D

2019-08-30 23:38 UTC, hashman requested changes
幾個東西調整一下

1. Social Media 頁面如果沒有提供那些連結，按鈕幫忙隱藏
2. **註記** 目前 Sponsor 頁面尚未完成，但完成要可以 Link 過去
3. 講者獨立頁面有實作嗎？

再請葉子幫忙看一下，謝謝

2019-08-30 23:38 UTC, hashman commented on 2019-dev/pages/speaker/SectionMasterSpeaker/index.vue
> +            content: `https://mopcon.org/2019/speaker/${speaker.speaker_id}`,
看到這個讓我想起來，獨立的講者頁面有實做嗎？另外是這邊要依照 `.env` 的 `BASE_URL` 來給，不可以 hard code 寫死唷～～

2019-08-30 23:38 UTC, hashman commented on 2019-dev/pages/speaker/SectionMasterSpeaker/index.vue
> +<style lang="scss" src="./style.scss" scoped></style>
幫我多一個空白行，謝謝

2019-08-31 00:56 UTC, Tzuhui commented
@hashman 需要調整的部分星期日回來後會一併調整～
另外，講者獨立頁面有實作哦
在後面加上 ?id=${id} 就會開啟該講者的資訊。例如：/2019/speaker?id=1
這部分再請 hash 看看這樣有沒有問題～～

2019-09-02 00:08 UTC, hashman commented
> speaker?id=1

ok 我看到了，謝謝，這邊想要請葉子幫忙調整一個東西，就是希望可以跟去年的獨立講者頁面一樣有個地方可以複製連結，方便大家進行分享，可以參考下圖

https://d.pr/i/o7fi8N

2019-09-02 16:23 UTC, Tzuhui commented
這個 commit 有調整了
- Social Media 沒有提供連結則按鈕隱藏
- head og-url 改取 env 的 BASE_URL
- 最後多一個空白行
- 分享講者按鈕取得連結的方式修改

另外有問題要詢問的部分：
https://github.com/MOPCON/MOPCON/pull/247#issuecomment-526964918
這個目前是打開講者 Modal 之後點選下方的『分享講者』按鈕，會複製 env 的 `BASE_URL` + `/2019/speaker?id=${id}`
只是沒有用 input 將連結顯示出來（因為設計稿上是沒有～
這部分再請 hash 看看是否正確，或是需要什麼調整

以上再麻煩 @hashman 看看，感謝 :D

2019-09-02 23:47 UTC, hashman approved these changes

2019-09-02 23:48 UTC, hashman commented
我先把這個 PR merge 進去，然後想請 @Tzuhui 幫我在「分享講者」按扭點下去的時候可以有些 reaction 這樣才知道有點擊到，謝謝

2019-09-02 23:48 UTC, merged