Update unconf api
MOPCON/MOPCON pull request #255
Opened 2019-09-04 16:17 UTC by Zames-Chang

@hashman

2019-09-05 01:20 UTC, hashman requested changes
Hi @Zames-Chang 有沒有更為簡單的方法？我們這次的目標是什麼？讓 unconf api 的結構可以跟 session api 的結構一致，如果要達成這個目標我們可以怎麼做？你目前的作法沒錯可以達成目標，但是確有幾個問題出現了

1. json 裡面有很多不必要的欄位需要先被 pre-defined 好
2. Maintainer 在維護這份 json 的時候需要寫過多的資訊

根據以上兩點有沒有辦法再改善這個作法呢？

2019-09-05 09:06 UTC, Zames-Chang commented
我看到 session 的做法了，我們只會記錄 speaker id 和 session id 之後再從 speaker.json 把資料拉出來，並且把格式修正成符合docs的格式是嗎?

2019-09-05 09:07 UTC, Zames-Chang commented
不過，有個問題是我知道交流場次都在3f，那在3f的都是交流場次嗎?

2019-09-05 09:08 UTC, hashman commented
> 不過，有個問題是我知道交流場次都在3f，那在3f的都是交流場次嗎?

交流場次都在 3F

2019-09-05 09:11 UTC, Zames-Chang commented
所以我從speaker拉資料的時候，我可以直接透過樓層來判斷是否為交流場次嗎?

2019-09-05 09:11 UTC, hashman commented
> 所以我從speaker拉資料的時候，我可以直接透過樓層來判斷是否為交流場次嗎?

不行，你的資料來源一樣是依賴 `unconf.json` 提供

2019-09-05 09:11 UTC, hashman commented
unconf 跟一般議程是不一樣的東西

2019-09-05 09:14 UTC, Zames-Chang commented
那我在 unconf-dev.json 中可以先隨機 link 到 speaker-dev 3f 的場次作為mock data?

2019-09-06 14:17 UTC, hashman requested changes
再麻煩 Zames 看看

2019-09-06 14:17 UTC, hashman commented on api/app/Http/Controllers/UnconfController.php
> +                "job_title_e" => "",
多於空白幫我清除，謝謝

2019-09-06 14:17 UTC, hashman commented on api/app/Http/Controllers/UnconfController.php
> +                print_r($unconf);
怎麼會有 print_r?

2019-09-06 14:17 UTC, hashman commented on api/app/Http/Controllers/UnconfController.php
> +        }
這邊有更精簡的作法，只要調整一些東西就可以了

```
private function mapMissingStructure()
  128     {
  129         // loop over everyday
~ 130         foreach ($this->jsonAry as $key => &$subset){
  131             // loop over every period
~ 132             foreach ($subset['period'] as $periodKey => &$periodSubset){
~_133                 $periodSubset = array_merge_recursive($this->missingStructure, $periodSubset);
  134             }
  135         }
  136     }
```

`private $missingStructure` 可以將 period 這個 index 拿掉

然後因為 unconf 同時間止會有一場，所以結構上可以將 `unconf-dev.json` 改為

```
[
  {
    "date": 1571414400,
    "period": [
      {
        "started_at": 1571447700,
        "ended_at": 1571450400,
        "room": {
          "name": "家佳",
          "name_e": "Hilbert Boyle",
          "speaker_id": 1,
          "topic": "Maxime nesciunt.",
          "topic_e": "Est aliquid sed eum quae in.",
          "started_at": 1571446800,
          "ended_at": 1571450400,
          "session_id": 2019101
        }
      }
    ]
  },
  {
    "date": 1571500800,
    "period": [
      {
        "started_at": 1571534100,
        "ended_at": 1571536800,
        "room": {
            "name": "家佳",
            "name_e": "Hilbert Boyle",
            "speaker_id": 2,
            "topic": "Maxime nesciunt.",
            "topic_e": "Est aliquid sed eum quae in.",
            "started_at": 1571533200,
            "ended_at": 1571536800,
            "session_id": 2019102
          }
      }
    ]
  }
]
```

這樣就可以更為簡潔

2019-09-06 14:20 UTC, Zames-Chang commented on api/app/Http/Controllers/UnconfController.php
> +                print_r($unconf);
OAO

2019-09-06 14:35 UTC, Zames-Chang commented on api/app/Http/Controllers/UnconfController.php
> +        }
`$periodSubset = array_merge_recursive($this->missingStructure, $periodSubset);`
這段不對應該是
$periodSubset = array_merge_recursive($this->missingStructure['period'], $periodSubset);

2019-09-06 14:41 UTC, Zames-Chang commented
OK 我做了一些調整 你在看看

2019-09-06 15:32 UTC, hashman commented on api/app/Http/Controllers/UnconfController.php
> +        }
其實我上面有寫到可以將 missingStructure 的結構改變一下就不用寫這個 periods 了，但沒關係

2019-09-06 15:34 UTC, hashman approved these changes
OK

2019-09-07 03:39 UTC, hashman commented
我沒有權限推你的 branch 所以我先將你的 branch close 掉另外開一個 branch 處理

2019-09-07 03:39 UTC, closed without merging