調整 community api & volunteer api
MOPCON/MOPCON pull request #257
Opened 2019-09-05 07:37 UTC by FWcloud916

@hashman ，麻煩幫我檢查。謝謝

2019-09-05 15:57 UTC, hashman requested changes
圖片的部分調整一下，謝謝

2019-09-05 15:57 UTC, hashman commented on api/app/Http/Controllers/CommunityController.php
> +        return response()->download($path);
試試看這樣，只是 png 那邊我希望可以是動態偵測檔案的負檔名的

```
return (new Response(file_get_contents($path), 200))->header('Content-Type', 'png');
```

2019-09-05 15:57 UTC, hashman commented on api/app/Http/Controllers/VolunteerController.php
> +        return response()->download($path);
試試看這樣，只是 png 那邊我希望可以是動態偵測檔案的負檔名的

```
return (new Response(file_get_contents($path), 200))->header('Content-Type', 'png');
```

2019-09-05 16:46 UTC, FWcloud916 commented
@hashman 調整了，麻煩再看看

2019-09-05 16:47 UTC, FWcloud916 commented on api/app/Http/Controllers/VolunteerController.php
> +        return response()->download($path);
原來可以這樣處理，謝謝~

2019-09-06 13:55 UTC, hashman approved these changes
LGTM

2019-09-06 13:56 UTC, merged