新增主辦社群頁面
MOPCON/MOPCON pull request #268
Opened 2019-09-07 16:30 UTC by Tzuhui

#210 主辦社群頁面完成了～
再請 @hashman review，謝謝 :D

2019-09-08 01:00 UTC, hashman requested changes
應該有少推 lock 檔，我 compile 不過

2019-09-08 01:00 UTC, hashman commented on 2019-dev/pages/community/SectionCommunity/index.vue
> +              }
這邊可以調整為 `vm.show = vm.show === id ? -1 : id;` 更為簡潔

2019-09-08 04:06 UTC, Tzuhui commented
compile 不過可能是因為 plugin 引入的方式，因為我一開始開發的時候是沒有出錯
這一次重新 run 就有問題了，所以就調整一下寫法，再請 @hashman  試試看這樣可否正確 compile

2019-09-08 23:15 UTC, hashman commented
@Tzuhui 根據 slack 的說明，我有安裝好這個套件了，但還是沒辦法 compile 通過，想請你幫我測試一下執行下述內容再進行一次 compile 確認是否還是可以成功 build 起來

```
rm yarn.lock && rm -rf node_modules/
yarn install
yarn add vue-lottie --save
yarn run generate
```

另外麻煩葉子幫我看一下你的 node 版本，謝謝

2019-09-09 05:32 UTC, Tzuhui commented
我照著指令一行一行貼，是可以正常 compile 出來的耶
我的 node 版本是 8.12.0

想問一下～
無法成功 build 有出現什麼錯誤的畫面嗎？

2019-09-09 14:44 UTC, closed without merging