新增主辦社群頁面
MOPCON/MOPCON pull request #280
Opened 2019-09-09 15:16 UTC by Tzuhui

新增主辦社群頁面，請 @hashman review～ 感謝

2019-09-09 23:35 UTC, hashman requested changes
Hello 葉子有幾個問題

1. 你有將 `yarn.lock` commit 上來了，但是沒有 commit 你需要安裝的套件，需要額外下 `yarn add vue-lottie --save` 才可以讓 `package.json` 與 `yarn.lock` 有 change 你試試看
2. 好像有少一些 asset 我在 build 的時候有發生找不到 asset 的問題

```
ERROR in ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&)
Module not found: Error: Can't resolve './images/Icon_instagram.png' in '/home/hashman/repo/MOPCON/2019-dev/pages/community/SectionCommunity'
 @ ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&) 1:1890-1928
 @ ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&
 @ ./pages/community/SectionCommunity/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&)
Module not found: Error: Can't resolve './images/Icon_telegram.png' in '/home/hashman/repo/MOPCON/2019-dev/pages/community/SectionCommunity'
 @ ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&) 1:2138-2175
 @ ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&
 @ ./pages/community/SectionCommunity/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&)
Module not found: Error: Can't resolve './images/Icon_twitter.png' in '/home/hashman/repo/MOPCON/2019-dev/pages/community/SectionCommunity'
 @ ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&) 1:1644-1680
 @ ./pages/community/SectionCommunity/index.vue?vue&type=template&id=7e8838b4&scoped=true&
 @ ./pages/community/SectionCommunity/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
```

再請 @Tzuhui 幫忙看看，謝謝

2019-09-10 11:50 UTC, hashman requested changes
`./images/lottie/animate.json` 這個檔案放在 images 會不會怪怪的？有沒有更好的位置可以擺放呢？

2019-09-10 11:50 UTC, hashman commented on 2019-dev/pages/community/SectionVolunteerTeam/index.vue
> +        <a href="/2019/sponsor" class="btn-primary">了解詳情</a>
連結先幫我換成 `https://drive.google.com/open?id=1fbjbdAOrs9hGy3r-DkMnyNl5eWgYJsKd` 謝謝

2019-09-10 13:51 UTC, Tzuhui commented
連結有修改了～
./images/lottie/animate.json 這個我改到 assets 下，感覺更適合些
再請 @hashman 看看，謝謝

2019-09-10 14:20 UTC, hashman approved these changes
LGTM

2019-09-10 14:20 UTC, merged