mod: update sponsor json
MOPCON/MOPCON pull request #288
Opened 2019-09-11 14:47 UTC by FWcloud916

@hashman @xwang0929 

sponsor 轉換的資料，先看看有沒有問題

2019-09-11 15:56 UTC, hashman commented
請 @xwang0929 中哥幫忙，謝謝

2019-09-12 01:27 UTC, xwang0929 requested changes
sponsor_id 型別要改 int，about_us_e 的欄位抓錯，其他都是中英文空格的問題。

測試資料再請 @hashman 確認一下。

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "about_us": "身為國內主機商，從網路主機代管起家的捕夢網，近年來為因應企業需求，轉型踏入資訊安全防護的領域。有別於其他網路服務業者，捕夢網提供網路架構的安全服務，更以客戶立場出發，注重網站暨程式的資訊安全服務。代理國內外SSL憑證，獨家代理來自以色列的弱點掃描、WAF應用程式防火牆及DAF資料庫防火牆等資安服務，打造加密、偵測、阻擋、掩護四點一環，全方位網站安全環境。累積多年
SSL/DAF 前後要加空白；WAF 後加空白

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "about_us": "MySQL是全球最受歡迎的開源資料庫，也是網路應用系統的首選資料庫，它為臉書、推特、YouTube、優步、雅虎以及其他許多網路巨擘的主要資料庫管理系統．相關訊息請參考 http://www.oracle.com",
MySQL 後加空白

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "about_us": "KKBOX是由一群熱愛技術及音樂的工程師於 2005 年創立的品牌，以獨創的雲端技術提供音樂串流服務，讓使用者透過網路即可播放儲存在雲端的歌曲；並以技術加密媒體檔成功為線上音樂和智慧財產權取得完美的平衡，打開了線上音樂合法授權的版權觀念，更成為亞洲市場的標竿品牌。至今，KKBOX 擁有超過 4500 萬首曲目，服務地區包括台灣、香港、日本、新加坡及馬來西亞。KK
有兩個 KKBOX 後面要加空白

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "about_us": "Verizon是美國首屈一指的電信公司，擁有在全美獲獎無數的無線網路和優質的全光纖網絡，並為全球企業提供完整的解決方案。透過Verizon媒體集團旗下的Yahoo、TechCrunch與HuffPost等品牌，我們致力於協助消費者隨時取得最新消息及娛樂內容、彼此溝通與進行交易，同時為廣告主及合作夥伴創造與消費者的全新連結。在台灣，我們持續提供Yahoo奇摩旗下包
英文前後如果是全型標點符號不用留空格，如果是中文字就加空白。Verizon / Yahoo / TechCrunch / HuffPost 都要修正。

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "sponsor_type": "tony_stark"
測試資料要拿掉

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "about_us": "BiiLabs 致力於使用分散式帳本技術解決萬物聯網帶來的挑戰，涵蓋智慧城市與能源管理等領域，其核心技術協助各產業之數位轉型，進而解決在客戶應用中的信任，安全，成長，效率等關鍵問題。BiiLabs期許成為萬物聯網世代的關鍵技術方案提供者。",
BiiLabs 後加空白

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "sponsor_type": "bruce_wayne"
測試資料要拿掉

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "sponsor_type": "bruce_wayne"
測試資料要拿掉

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "about_us": "KlickKlack 以亞洲為主要服務區域，於台灣、香港、新加坡皆有不同的事業體，服務項目含括資訊網路建置、滲透測試監管與稽核服務、電影後期、廣告執行製作、品牌設計、形象包裝。可立可股份有限公司KlickKlack Communications 是 KlickKlack 集團的一員。提供專業的資通訊服務，除了累積了近千場的活動執行經驗之外，也為數十家新創公司建置
KlickKlack Communications 前面留空白

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "about_us": "IPIP.NET专注于 IP 地理位置以及 IP 画像数据的研究、整理与发行。我们的主力产品 IP 地理位置数据库主要基于 BGP/ASN 数据以及遍布全球的网络监测点进行城市级 IP 地域数据标注，准确度远高于国内国外同类产品。我们的客户遍布于各类型互联网公司，比较集中在网络安全行业、电商行业、娱乐行业、金融行业、硬件行业，以及 CDN、DNS、VPN、视频、
IPIP.NET 後留空白

2019-09-12 01:27 UTC, xwang0929 commented on api/resource/assets/json/sponsor.json
> +    "about_us": "我們是一間總部位於新加坡的軟體開發公司，專注於遊戲和娛樂產業，採用敏捷開發同時全面導入敏捷管理，在多次的嚐試與挫折學習後，逐漸形塑出鈦坦科技坦率透明的核心價值，以人為本的管理方式，獲得亞洲知名人力刊物 HR Asia「2019台灣最佳企業雇主獎」。在這裡沒有Boss，但要有自組織的Guts，我們重視團隊合作勝於個人英雄主義，不再實施個人績效評量、實行彈性工時、實
Boss / Guts 前留空白

2019-09-13 03:18 UTC, FWcloud916 commented
@hashman @xwang0929 再看看

2019-09-13 05:23 UTC, xwang0929 approved these changes
LGTM

2019-09-13 05:31 UTC, hashman commented
@FWcloud916 我打 API 是無法正常運作的，要不要檢查一下呢？

2019-09-13 08:16 UTC, xwang0929 commented
拍謝，沒有試打 api，幫忙找 bug。
原因是 production json 裡有個 sponsor_type 是"其他"，原本的 controller 沒有處理到這個就報錯了

2019-09-13 08:23 UTC, FWcloud916 commented
> 拍謝，沒有試打 api，幫忙找到 bug 了。
> 原因是 production json 裡有個 sponsor_type 是"其他"，原本的 controller 沒有處理到這個就報錯了

@hashman '其他' 是不是要改成別的名稱，'教育' 之類的
我們要不要整理一下一次調整

2019-09-13 13:13 UTC, FWcloud916 commented
@hashman @xwang0929 
先調整了，不過我覺得叫 "其他" 可能有些不合適，應該要再調整

2019-09-13 14:15 UTC, FWcloud916 commented
'其他' 都先歸為'特別感謝'，六角歸為教育

2019-09-13 14:15 UTC, FWcloud916 commented
@hashman @xwang0929 再看看

2019-09-13 14:47 UTC, FWcloud916 commented
LOGO 的圖還沒有

2019-09-13 23:46 UTC, hashman commented
@FWcloud916 我想要先將這個 PR WIP 起來，因為贊助組那邊都還沒有回應我說哪些贊助商是需要先 relesae 的，想要等東西到期我在 merge ，另外還有圖片也還沒 ready

2019-09-14 04:47 UTC, FWcloud916 commented
ok

2019-09-21 16:51 UTC, FWcloud916 commented
- 缺 logo : 天瀧書局、NCKU_CSIE
- 缺 data :  hackmd、 NCKU_CSIE
- 資料僅有名稱 : 南星創速器股份有限公司、六角學院、天瓏書局

2019-09-21 23:45 UTC, hashman commented
@FWcloud916 幫我 rebase 一下，謝謝

2019-09-21 23:58 UTC, hashman requested changes
天瓏就先把他移除好了，然後 code 有個 bug 想請你幫忙調整一下

幫我將 `SponsorController` 中的 `getAllSponsors` 與 `getSpecificSponsors` 組成 `$data` 的時候幫我補個 `ksort` function 排序一下

出來的順序有點問題

2019-09-22 02:23 UTC, FWcloud916 commented
@hashman 好了

2019-09-22 04:34 UTC, hashman approved these changes
LGTM 我等贊助組回應

2019-09-22 13:32 UTC, merged