新增贊助商頁面
MOPCON/MOPCON pull request #293
Opened 2019-09-12 12:33 UTC by Tzuhui

#211 新增贊助商頁面
再請 @hashman review～ 謝謝

2019-09-12 15:52 UTC, hashman requested changes
請 @Tzuhui 幫忙，謝謝

2019-09-12 15:52 UTC, hashman commented on 2019-dev/pages/sponsor/SectionPartner/index.vue
> +          .$get(`/api/2019/sponsor`)
sponsor 其實有可以取得單一 sponsor 的 api 要不要用那個就好？

2019-09-12 15:52 UTC, hashman commented on 2019-dev/pages/sponsor/index.vue
> +      <div class="slider sponsor_carrousel">
這邊幫我將 http://mopcon.hashman.tw/2019/_nuxt/img/81d7887.png 這個圖片拿掉，我堅持，謝謝

2019-09-12 15:52 UTC, hashman commented on 2019-dev/pages/sponsor/SectionSponsor/index.vue
> +    <section class="section section-sponsor">
因為目前招募已經停止了，這個 sesion 可以拿掉，或是說可以用個參數來控制這塊要不要 show 出來

2019-09-13 05:30 UTC, Tzuhui commented
comment 上的問題有調整了，再麻煩 @hashman  看看
謝謝 :D

2019-09-14 00:47 UTC, hashman approved these changes
ok

2019-09-14 00:48 UTC, merged