Add redis for facebook api
MOPCON/MOPCON pull request #296
Opened 2019-09-13 09:39 UTC by Zames-Chang

#256 

設定上要將 api 資料夾中 `.env` 修改
CACHE_DRIVER=redis

我在這台的電腦的 redis 配置
host: 127.0.01
port: 6739

我使用 lumen 提供的 redis 套件來完成，使用的都是預設的設定，不確定是否在 dev 的環境上 redis 的設定是否有所不同。

2019-09-14 04:40 UTC, hashman requested changes
Hi @Zames-Chang  幾個問題看一下

1. 通常 cache 裡面只會放 data 不會將整個 response result 都放進去，目前的寫法會將整個 response 都放進去
2. `requestFacebookApi` 這個 function 在任何狀況下都會 return json 回去，本身沒有問題但是將 token invalid, request error 這類的東西也放入 cache 這個是預期的嗎？如果不是該怎麼處理比較適合？
3. 看你安裝 composer 的指令 `composer require illuminate/redis:5.8.*` 是沒錯的，但是我的 `composer.lock` 的內容跟你不太一樣，你同時也更新了很多的套件，這部分是不是要多下其他的指令呢？我的 `composer.lock` 只更新了 2 個套件，但是你確有 712 個 code change 好像哪裡怪怪的？
4. `$app->withEloquent();` 這個是必要的？
5. 目前 cache 的時間設定為 20 分鐘，好像有點久，可能 10 分鐘會比較適合

以上有問題都可以提出討論，謝謝

2019-09-14 06:06 UTC, Zames-Chang commented
1. 修正了現在只有 data 的欄位會被塞進 redis
2. 現在只有 return 狀態成功才會被塞進 redis
3. 修正成只要多update illuminate/contracts 而不是全部一起update
4. 根據 https://lumen.laravel.com/docs/6.x/cache `敘述，如果不設定那個則要設定`$app->configure('database');`
`if you have not called $app->withEloquent() in your bootstrap/app.php file, then you should call  $app->configure('database'); in the bootstrap/app.php file to ensure the Redis database configuration is properly loaded.`
5. 修正為十分鐘

2019-09-14 06:39 UTC, hashman requested changes
請 Zames 看看，謝謝

2019-09-14 06:39 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        return $this->returnSuccess('Success get posts', $facebookPostsArr['data']);
目前的作法所獲得的 result 是正確的沒問題，但目前的寫法有一個問題
1. 如果 `$this->dataProcesser` return 的 `$response['success']` 是 false 的話，還是會回傳 success 為 true ，可以仔細看一下 `dataProcesser` 那邊
2. 目前 private function 都會使用 `ApiTrait` 的 function 進行回傳，這個行為沒問題，但你可以看看，他的 response 基本上你需要只有 data 這邊應該可以再優化一下

2019-09-14 09:05 UTC, Zames-Chang commented on api/app/Http/Controllers/FacebookController.php
> +        return $this->returnSuccess('Success get posts', $facebookPostsArr['data']);
1. 改成直接回傳 `$this->dataProcesser` 的結果應該可以解決這個問題
2. 這部分我有點沒聽懂，因為在 `if ($facebookPostsArr['success'])` 這個欄位，我不只需要 `data` 我還需要  `success`  才能判對回傳的結果要不要放到 redis 裡面以避免錯誤訊息被放到 redis

2019-09-14 12:01 UTC, hashman commented on api/app/Http/Controllers/FacebookController.php
> +        return $this->returnSuccess('Success get posts', $facebookPostsArr['data']);
那有沒有方法是可以不要透過 success 這個欄未來知道有沒有成功呢？又或者是說，當我今天執行到最後一個步驟他就一定是成功的呢？

我該如何做到這個方法呢？可以參考 try catch 這個東西

2019-09-17 13:49 UTC, Zames-Chang commented
修正 dataProcesser and requestFacebookApi 若有錯誤會丟出 Exception 然後 return error
@hashman 
```
那有沒有方法是可以不要透過 success 這個欄未來知道有沒有成功呢？又或者是說，當我今天執行到最後一個步驟他就一定是成功的呢？

我該如何做到這個方法呢？可以參考 try catch 這個東西
```

2019-09-17 22:31 UTC, hashman approved these changes

2019-09-17 22:31 UTC, merged