mod: 更新講者及議程資訊
MOPCON/MOPCON pull request #300
Opened 2019-09-19 01:38 UTC by FWcloud916

@hashman @xwang0929 在麻煩看一下喔，謝謝
- 輸出 \n (這個先加上去了，要確認前端會不會有問題)
- 沒有照片的講者，先顯示 volunteers/aganda 的圖片
- 調整中英文空白
- 新增 5 位講者

2019-09-19 02:13 UTC, FWcloud916 commented
> * 輸出 \n (這個先加上去了，要確認前端顯示上會不會有問題)
剛測試這個，網頁沒有處理\n，需要先拿掉嗎?

2019-09-19 05:16 UTC, FWcloud916 commented
調整 speaker 跟 session 的取代，改用正則表達式過濾

2019-09-19 08:38 UTC, FWcloud916 commented
rebase

2019-09-19 13:41 UTC, xwang0929 approved these changes
LGTM

2019-09-19 17:02 UTC, FWcloud916 commented
@hashman @xwang0929 在幫忙看一下，謝謝
- 補上圖片
- 時間修正

2019-09-20 00:47 UTC, hashman requested changes
敏結論壇幫我補上 Hermes 謝謝

2019-09-20 00:47 UTC, hashman commented on api/resource/assets/json/speaker.json
> +    "started_at": 1571474400,
開始時間錯了

2019-09-20 01:30 UTC, FWcloud916 commented
@hashman @xwang0929 
調整了，在麻煩一下

2019-09-20 01:30 UTC, hashman approved these changes

2019-09-20 01:30 UTC, merged