電子看板 Api
MOPCON/MOPCON pull request #342
Opened 2019-10-16 01:19 UTC by FWcloud916

@hashman @xwang0929 麻煩幫我檢查，謝謝

2019-10-16 03:50 UTC, FWcloud916 commented
修正 doc 中 json 格式

2019-10-16 05:09 UTC, xwang0929 requested changes
api/resource/assets/images/board/sponsor/sponsor_3.jpg 這張圖的解析度有點小。

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +  - play_time: 輪播切換時間
play_time 沒有標示 type

2019-10-16 05:09 UTC, xwang0929 commented on api/app/Http/Controllers/BoardController.php
> +                    'play_time' => $this::PLAY_TIME_SESSION,
PLAY_TIME_SESSION or PLAY_TIME_AD?

2019-10-16 05:09 UTC, xwang0929 commented on api/app/Http/Controllers/BoardController.php
> +        $map = [
map 跟其他的 content 結構不一致是刻意的嗎？

2019-10-16 05:09 UTC, xwang0929 commented on api/app/Http/Controllers/BoardController.php
> +        date_default_timezone_set("Asia/Taipei");
timezone 應該統一從 config 或 .env 設定，這邊看不出來有特別處理的需求。

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +        - tags(array): 議程標籤
這個 tags 好像只是用來標示是否開放錄影，我一直以為是議程原本的 tags。如果我沒誤會的話，請補充說明。

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +          - name(string): 標籤名稱
少了 session_id 欄位

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +        - tags(array): 議程標籤
同上面的 tags

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +          - name(string): 標籤名稱
同上面的 session_id

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +  - data(for ad)
少了 type 欄位

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +    - sponsor_ad_img: 贊助商電子看板圖片
格式與實際 json 不符

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +    - play_time: 輪播時間
同上面的 play_time

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +    - play_time: 輪播時間
同上面的 play_time

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +  - data(for map)
少了 type 欄位 (是故意的嗎？)

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +    - map:地圖圖片
上面欄位都沒有標示 type

2019-10-16 05:09 UTC, xwang0929 commented on api/docs/board.md
> +          subtitle: "",
title 跟 subtitle 補一下資料。type 欄位如果是漏掉的話這邊也要補。

2019-10-16 05:09 UTC, xwang0929 commented on api/app/Http/Controllers/BoardController.php
> +            if (($now >= $start_after && $now < $next_before_start) || $before_start > $now) {
要加上判斷議程是否已經結束，否則會有議程已結束卻一直出現在看板上並顯示議程預告。例：
時間 2019/10/19 10:10 會出現 HI AI 的議程預告。

2019-10-16 07:33 UTC, FWcloud916 commented on api/docs/board.md
> +  - data(for map)
補上了

2019-10-16 07:35 UTC, FWcloud916 commented on api/docs/board.md
> +        - tags(array): 議程標籤
有補充說明了，分為 禁止攝影/議程現場/同步轉播 三種

2019-10-16 07:44 UTC, FWcloud916 commented on api/app/Http/Controllers/BoardController.php
> +        date_default_timezone_set("Asia/Taipei");
我自己忘記設定了XD
這邊需要在 .env 設定時區為 台北時間 不然議程判斷會出錯。

2019-10-16 07:44 UTC, FWcloud916 commented on api/app/Http/Controllers/BoardController.php
> +        $map = [
漏掉了，已修正

2019-10-16 07:44 UTC, FWcloud916 commented on api/app/Http/Controllers/BoardController.php
> +                    'play_time' => $this::PLAY_TIME_SESSION,
修正了

2019-10-16 07:45 UTC, FWcloud916 commented on api/app/Http/Controllers/BoardController.php
> +            if (($now >= $start_after && $now < $next_before_start) || $before_start > $now) {
有調整了

2019-10-16 07:45 UTC, FWcloud916 commented
data 有三種格式，不會同時出現
content 的實際內容為
- content(array)
  - type(string): session/ad/map
  - play_time(int): 輪播切換時間，單位為秒
  - data(array): 輪播內容 session/ad/map

我有補充在 doc 中

2019-10-16 07:46 UTC, FWcloud916 commented
再麻煩 @xwang0929 幫我檢查

2019-10-16 09:41 UTC, xwang0929 requested changes
文件再調整一下就沒問題了

2019-10-16 09:41 UTC, xwang0929 commented on api/docs/board.md
> +    - map:地圖圖片
這邊的資料型別沒有補到

2019-10-16 09:41 UTC, xwang0929 commented on api/docs/board.md
> +                "session_id": 2019001,
文件沒有拿掉 session_id

2019-10-16 09:41 UTC, xwang0929 commented on api/docs/board.md
> +                  "session_id": 2019001,
文件沒有拿掉 session_id

2019-10-16 09:41 UTC, xwang0929 commented on api/docs/board.md
> +                  "session_id": 2019001,
文件沒有拿掉 session_id

2019-10-16 09:41 UTC, xwang0929 commented on api/docs/board.md
> +        }
文件範例與實際內容不符

2019-10-16 09:53 UTC, FWcloud916 commented
@xwang0929 調整了

> api/resource/assets/images/board/sponsor/sponsor_3.jpg 這張圖的解析度有點小。

這張我有問一下贊助組，說沒關係

2019-10-16 10:00 UTC, xwang0929 approved these changes
LGTM

2019-10-16 14:20 UTC, hashman requested changes
大致上測試，除了有個 bug 之外，其他的沒有什麼太大的問題，幾個東西幫忙也調整一下

1. 有些 function 都有加上 blockdoc 就全部都補上去吧
2. 每個 function 的 parameter 都定義他的行別與 return type 吧

這邊再請 Eric 幫忙，謝謝

2019-10-16 14:20 UTC, hashman commented on api/app/Http/Controllers/BoardController.php
> +    protected $session_keys = [
好奇問一下，為什麼要分 private 跟 protected?

2019-10-16 14:20 UTC, hashman commented on api/app/Http/Controllers/BoardController.php
> +        $day = strtotime(date('Ymd', $now));
這邊有 bug ，我如果現在的時間是 1571447640 也就是 2019/10/19 09:14:00 的話，取到的 `$day` 會是 1571443200 也就是 10/18 16:00 ，用這樣的寫法應該就沒問題了

```
$current = Carbon::createFromTimestamp($now, 'Asia/Taipei');
$day = Carbon::create($current->year, $current->month, $current->day, 0, 0, 0, 'Asia/Taipei')->getTimestamp();
```

2019-10-16 14:20 UTC, hashman commented on api/app/Http/Controllers/BoardController.php
> +        $main_room = $sidecar_room = [];
如果是連播議程的話， sidecar 好像也會都是一樣的內容，這個是預期的嗎？

2019-10-16 14:20 UTC, hashman commented on api/app/Http/Controllers/BoardController.php
> +
多餘空白幫我移除唷

2019-10-16 14:20 UTC, hashman commented on api/app/Http/Controllers/BoardController.php
> +
多餘空白幫我移除唷

2019-10-16 17:17 UTC, FWcloud916 commented
@hashman 調整了，在麻煩看一下

2019-10-17 01:46 UTC, hashman approved these changes
LGTM

2019-10-17 01:47 UTC, merged