調整 CFS
MOPCON/MOPCON pull request #372
Opened 2020-07-05 15:59 UTC by Tzuhui

CFS 調整，請 @hashman review~ 感謝 :D

2020-07-08 04:23 UTC, hashman commented
我覺得呈現起來稍嫌有點小，葉子覺得呢？

https://d.pr/i/avFLZ5

2020-07-12 15:21 UTC, Tzuhui commented
有和設計師確認改為 250px

2020-07-13 12:28 UTC, hashman requested changes
instagram 的 link 幫忙調整成 https://www.instagram.com/mopcon.tw/

2020-07-13 12:28 UTC, hashman commented on 2020-dev/pages/cfs.vue
> +              享有在人潮多處的靜態曝光，和實體交流unconference。
unconference 前面多一個空白

2020-07-13 12:28 UTC, hashman commented on 2020-dev/pages/cfs.vue
> +                  ICCK大門兩側全版廣告空間
ICCK 後面增加空白

2020-07-13 12:28 UTC, hashman commented on 2020-dev/pages/cfs.vue
> +                <p>迎賓袋放入公司產品/文宣/問卷</p>
迎賓袋放入公司產品 / 文宣 / 問卷

2020-07-13 12:28 UTC, hashman commented on 2020-dev/pages/cfs.vue
> +              享有在人潮多處的靜態曝光，和實體交流unconference。
應該要統一都用 UnConference

2020-07-13 12:28 UTC, hashman commented on 2020-dev/pages/cfs.vue
> +            VIP入場套票
VIP 入場套票

2020-07-13 12:28 UTC, hashman commented on 2020-dev/pages/cfs.vue
> +            (每套入場套票含入場門票+晚宴入場券一張)<br>
(每套入場套票含入場門票 + 晚宴入場券一張)

2020-07-13 12:28 UTC, hashman commented on 2020-dev/pages/cfs.vue
> +            Meet.jobs透過其系統媒合企業與會眾，並於會後提供線上面試的系統服務，只收取確定錄取者的年薪8%作為服務費。
Meet.jobs 透過其系統媒合企業與會眾，並於會後提供線上面試的系統服務，只收取確定錄取者的年薪 8% 作為服務費。

2020-07-13 12:28 UTC, hashman commented on 2020-dev/layouts/default.vue
>                歷年MOPCON
歷年 MOPCON

2020-07-13 17:10 UTC, Tzuhui commented
1. 已調整以上中英文空格內容
2. CFS 內容調整：
- ICCK 大門兩側全版廣告空間改 x x x v
- 主動線攤位：1,200 名改為千名
3. 加上網站 meta
再請 @hashman 看看，感謝

2020-07-14 15:16 UTC, hashman approved these changes

2020-07-14 15:16 UTC, hashman commented
LGTM

2020-07-14 15:16 UTC, merged