更新 CFS 頁面、拿掉 header CFS 導向連結
MOPCON/MOPCON pull request #376
Opened 2020-07-16 14:26 UTC by Tzuhui

- 更新 CFS 頁面內容
- 調整 CFP 內容書寫空格
- 拿掉  header 的 CFS 導向連結

再請 @hashman review，感謝

2020-07-17 13:47 UTC, hashman requested changes
小調整

2020-07-17 13:47 UTC, hashman commented on 2020-dev/pages/cfp.vue
> +            MOPCON (Mobile Open Platform Conference) 行動科技年會，是<span>南台灣最大型的千人科技研討會</span>，曾獲 iThome 列為 2015 年<span>台灣三大開源年會之一</span>。MOPCON 聚集了千名會眾、百位志工、50 名以上講師、20 家以上企業、10 組以上社群團體。
百位志工、 50 名以上講師、 20 家以上企業、 10 組以上社群團體

2020-07-17 14:29 UTC, Tzuhui commented
已調整，再請 @hashman review~ 感謝

2020-07-18 01:22 UTC, hashman approved these changes

2020-07-18 01:22 UTC, merged