調整官網 API 架構
MOPCON/MOPCON pull request #382
Opened 2020-07-29 02:06 UTC by FWcloud916

#381
請 @hashman 幫忙 review

架構調整 : 
1. 建立 Year2019 資料夾  `app\Http\Controllers\Year2019`
2. 調整 2019 Api 的 namespace 

facebook api : 
因為內容完全一樣，不做抽象，直接用 router 區分

之後 2020 的 Web API 大致上會跟 2019 的邏輯相似
所以之後須將 2019 Api 的邏輯 抽象出來
controller 預計放在  Year2020 資料夾 (  `app\Http\Controllers\Year2020` )
抽象出來的放置在 Service ( `app\Service` )

資料的存放方式先維持跟去年一樣以人工更新

2020-07-29 02:10 UTC, FWcloud916 commented
也請 @unciax @a8264347 幫忙看看有沒有問題

2020-07-29 08:11 UTC, hashman requested changes

2020-07-29 08:11 UTC, hashman commented on api/app/Http/Controllers/Year2019/AppHomeController.php
> +namespace App\Http\Controllers\Year2019;
Year 我覺得有點多餘 xDDDD 我是覺得可以單純 2019 就好

2020-07-29 08:11 UTC, hashman commented on api/routes/web.php
> +        $router->get('initial', 'Year2019\InitialController@index');
應該可以用 route namespace 來處理，可以省不少東西

https://lumen.laravel.com/docs/6.x/routing#route-group-namespaces

2020-07-29 08:27 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2019/AppHomeController.php
> +namespace App\Http\Controllers\Year2019;
PHP 不准 XD

2020-07-29 08:28 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2019/AppHomeController.php
> +namespace App\Http\Controllers\Year2019;
https://www.php.net/manual/en/language.namespaces.rationale.php#104196

我的編輯器會有紅色波浪

2020-07-29 09:01 UTC, hashman commented on api/app/Http/Controllers/Year2019/AppHomeController.php
> +namespace App\Http\Controllers\Year2019;
OK

2020-07-29 09:06 UTC, FWcloud916 commented on api/routes/web.php
> +        $router->get('initial', 'Year2019\InitialController@index');
OK

2020-07-30 14:44 UTC, unciax approved these changes

2020-07-30 15:28 UTC, a8264347 approved these changes

2020-07-30 16:30 UTC, merged