Add2020 volunteer and community controller
MOPCON/MOPCON pull request #393
Opened 2020-08-18 16:52 UTC by a8264347

#389 繼承 volunteer and community controller 把 dev.json 先拉出來在環境develop測試
把設計稿 volunteer 圖片抓取出來 測試可以使用

2020-08-19 15:31 UTC, unciax requested changes
稍微看了一下，我覺得有些東西也可以搬回 BaseController ，有在檔案裡面留言，不知道 @hashman  跟 @FWcloud916  的意見為何?

另外，檔案結尾需要有一行空行哦
`api/app/Http/Controllers/CommunityController.php`
`api/app/Http/Controllers/VolunteerController.php`
`api/app/Http/Controllers/Year2020/CommunityController.php`
`api/app/Http/Controllers/Year2020/VolunteerController.php`

2020-08-19 15:31 UTC, unciax commented on api/app/Http/Controllers/CommunityController.php
> +namespace  App\Http\Controllers; // @todo: 这里是要生成类的命名空间
移除不需要或已完成的 @todo

2020-08-19 15:31 UTC, unciax commented on api/app/Http/Controllers/VolunteerController.php
> +namespace  App\Http\Controllers; // @todo: 这里是要生成类的命名空间
移除不需要或已完成的 @todo

2020-08-19 15:31 UTC, unciax commented on api/app/Http/Controllers/VolunteerController.php
> +Class VolunteerController extends Controller {  // @todo VolunteerController 这里是要生成的类名字
移除不需要或已完成的 @todo

2020-08-19 15:31 UTC, unciax commented on api/app/Http/Controllers/Year2019/CommunityController.php
> +use App\Http\Controllers\CommunityController as BaseCommunityController;
這邊不考慮直接把 App\Http\Controllers 底下的 CommunityController 命名為 BaseCommunityController 的原因為?

2020-08-19 15:31 UTC, unciax commented on api/app/Http/Controllers/Year2019/CommunityController.php
>      protected $function = 'community';
我覺得 $function 跟 index() 其實也可以放進 BaseController 裡面

cc @hashman , @FWcloud916

2020-08-19 15:58 UTC, a8264347 commented
空格跟TODO有修正囉

2020-08-20 01:30 UTC, hashman commented on api/app/Http/Controllers/Year2019/CommunityController.php
>      protected $function = 'community';
可以

2020-08-20 01:37 UTC, hashman requested changes
一些 coding style 的小問題，因為 MOPCON 的 project 已經是 PHP 7.2 的環境了，所以如果可以是希望可以統一補上 parameter type hint 與 return type ，有問題可以再提問，謝謝

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/CommunityController.php
> +namespace  App\Http\Controllers;
多餘空白請移除

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/CommunityController.php
> +use Illuminate\Http\Request;
這個應該沒有使用到

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/CommunityController.php
> +     * @return \Illuminate\Http\Response
return type 錯了

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/CommunityController.php
> +     * @return \Illuminate\Http\Response
return type 錯了

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/CommunityController.php
> +    public function imagesView($name)
統一補上 docblock 與 parameter type

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/Year2019/CommunityController.php
>  use Illuminate\Http\Response;
上面兩個沒有使用到

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/Year2019/VolunteerController.php
>  use Illuminate\Http\Response;
上面兩個沒有使用到

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/Year2020/CommunityController.php
> +use Illuminate\Http\Response;
上面兩個沒有使用到

2020-08-20 01:37 UTC, hashman commented on api/app/Http/Controllers/Year2020/VolunteerController.php
> +use Illuminate\Http\Response;
上面兩個沒有使用到

2020-08-20 01:40 UTC, hashman commented
另外是有關 git branch naming convention 的部分，可以參考這篇[文章](https://deepsource.io/blog/git-branch-naming-conventions/)，像是可以使用 `feature-xxx` 來作為 branch name ，看起來也會更為清楚

有關 commit 的部分是 Nice to have 的地方，可以善用 rebase 的技巧將一些 fixup 的 commit rebase 回原本的 commit ，這樣 commit 會看起來更為清楚乾淨，謝謝

2020-08-21 01:06 UTC, a8264347 commented
感謝指導，今日再修正。

2020-08-23 02:49 UTC, FWcloud916 requested changes
@a8264347 這邊再麻煩調整一下，謝謝

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2020/CommunityController.php
> +}
這跟 base controller 的看起來是一樣的，應該可以不用留著

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/VolunteerController.php
> +	use ApiTrait;
這邊是 Tab 麻煩改 4 個空格

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/VolunteerController.php
> +Class VolunteerController extends Controller {
class 改全小寫

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/CommunityController.php
> +Class CommunityController extends Controller {
class 改全小寫

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/CommunityController.php
> +	use ApiTrait;
Tab 改 4 個空格

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2020/CommunityController.php
> +    protected $function = 'community';
這個拉出去了，這邊就不用寫了

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2020/VolunteerController.php
> +    }
這跟 base controller 的看起來是一樣的，應該可以不用留著

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2020/VolunteerController.php
> +use Illuminate\Http\Response;
＠a8264347 這好像沒改到喔

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2020/VolunteerController.php
> +    protected $function = 'volunteer';
這已經提出去了，應該可以不用留了

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2019/CommunityController.php
空白行幫忙移除

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2020/CommunityController.php
> +
空白行幫忙移除

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2020/VolunteerController.php
> +
空白行幫忙移除

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/Year2020/CommunityController.php
> +use Illuminate\Http\Response;
＠a8264347 這好像沒改到喔

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/VolunteerController.php
> +use Illuminate\Http\Request;
這個好像沒用到喔

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/VolunteerController.php
> +Class VolunteerController extends Controller {
`{` 要先空行

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/VolunteerController.php
> +        	return $this->returnNotFoundError();
這邊有 Tab 麻煩改 4 個空白

2020-08-23 02:49 UTC, FWcloud916 commented on api/app/Http/Controllers/CommunityController.php
> +Class CommunityController extends Controller {
`{` 要先空行

2020-08-24 17:10 UTC, FWcloud916 approved these changes
LGTM

2020-08-24 17:24 UTC, FWcloud916 requested changes

2020-08-24 17:24 UTC, FWcloud916 commented on api/app/Http/Controllers/VolunteerController.php
> +}
這個檔案是忘記刪掉嗎？

2020-08-24 17:25 UTC, FWcloud916 commented on api/app/Http/Controllers/VolunteerController.php
> +}
@a8264347 好像多一個檔案喔 XD

2020-08-24 23:58 UTC, a8264347 commented
@FWcloud916 一個遺漏，再麻煩幫我看看哪裡有問題XD!

2020-08-25 01:24 UTC, FWcloud916 approved these changes
LGTM

2020-08-25 02:35 UTC, merged