新增 2020 講者 api
MOPCON/MOPCON pull request #396
Opened 2020-08-22 01:31 UTC by unciax

See #388

未完成部分：
1. 資料更新 (目前拿 2019 資料測試)
2. tag 部分尚不確定今年標色的狀況，或許可以考慮改用設定檔方式處理

2020-08-22 01:59 UTC, unciax commented
再請 @FWcloud916 幫忙 review 謝謝

2020-08-23 01:34 UTC, hashman requested changes
其他的我沒問題了

2020-08-23 01:34 UTC, hashman commented on api/app/Http/Controllers/BaseSpeakerController.php
> +        $path = end($path);
這邊加上一個判斷好了，目前沒有設定 2020 的圖檔，看看能不能先給個預設圖，或是有個 fallback 的機制

2020-08-23 03:10 UTC, unciax commented on api/app/Http/Controllers/BaseSpeakerController.php
> +        $path = end($path);
看起來這段只有針對空值才會改用議程組的圖片，這段我再補一下

2020-08-23 03:19 UTC, unciax commented on api/app/Http/Controllers/BaseSpeakerController.php
> +        $path = end($path);
剛重看了一下程式，沒有抓到圖片時會 fallback 去抓議程組的圖片
這部分 Edmond 的 PR 有設定進去，這樣這部分還有需要調整嗎?

2020-08-23 03:32 UTC, hashman commented on api/app/Http/Controllers/BaseSpeakerController.php
> +        $path = end($path);
如果有處理就不用額外處理沒關係

2020-08-24 17:36 UTC, FWcloud916 approved these changes
LGTM

2020-08-25 02:43 UTC, merged