新增 2020 電子看板 Api
MOPCON/MOPCON pull request #459
Opened 2020-10-09 03:10 UTC by unciax

See #451

2020-10-09 03:10 UTC, unciax commented
再麻煩 @FWcloud916 Review 了

2020-10-09 15:56 UTC, FWcloud916 requested changes
@unciax 幫我調整一下 coding style，其他沒有問題，感謝

2020-10-09 15:56 UTC, FWcloud916 commented on api/app/Http/Controllers/BaseBoardController.php
> +        }
```suggestion
                for ($i = 1; $i <= $slice_num; $i++) {
                    unset($list[$total_num - $i]);
                }
```
code style

2020-10-09 15:56 UTC, FWcloud916 commented on api/app/Http/Controllers/BaseBoardController.php
> +            $totalPlayTime =BaseBoardController::INROOM_PLAY_TIME_TOTAL;
```suggestion
            $totalPlayTime = BaseBoardController::INROOM_PLAY_TIME_TOTAL;
```
code style

2020-10-09 15:56 UTC, FWcloud916 commented on api/app/Http/Controllers/BaseBoardController.php
> +        $dir = $this->imgPath . 'board/'. $type . '/' . $name . '.*';
```suggestion
        $dir = $this->imgPath . 'board/' . $type . '/' . $name . '.*';
```

2020-10-09 16:26 UTC, unciax commented
調整完畢，再麻煩 @FWcloud916 確認一下

2020-10-12 03:22 UTC, FWcloud916 approved these changes
LGTM

2020-10-12 03:22 UTC, merged