Add sponsor page
MOPCON/MOPCON pull request #554
Opened 2021-09-08 15:54 UTC by yuuuna

issue #549 

Memo
* sponsor json 目前使用 2020 的資料
* 部分顯示圖片還未提供

2021-09-09 14:09 UTC, Tzuhui requested changes

2021-09-09 14:09 UTC, Tzuhui commented on 2021-dev/pages/sponsor/index.vue
> +    margin-right: 6%;
這個在行動版可以拿掉，讓區塊的邊是貼齊的～

2021-09-09 14:35 UTC, yuuuna commented on 2021-dev/pages/sponsor/index.vue
> +    margin-right: 6%;
已修正~

2021-09-12 07:54 UTC, Tzuhui commented on 2021-dev/pages/sponsor/index.vue
> +    margin-right: 6%;
這個只要行動版拿掉就好，桌面版的 margin 可以留著哦

2021-09-15 11:38 UTC, Tzuhui approved these changes

2021-09-15 11:38 UTC, merged