Copied 2020 json files to 2022 folder and tested them for api.
MOPCON/MOPCON pull request #612
Opened 2022-08-09 02:23 UTC by loxyz-tw

Copied 2020 json files to 2022 folder and tested them for api.

2022-08-09 15:19 UTC, keith222 approved these changes

2022-08-10 04:45 UTC, unciax requested changes
非 `-dev.json` 結尾的檔案內容都先放空陣列好了，也可以避免誤發佈出去

2022-08-10 14:25 UTC, unciax approved these changes
LGTM

2022-08-10 14:26 UTC, keith222 approved these changes

2022-08-10 14:27 UTC, merged